// packages/svelte-project/src/App.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import todoStore from "./lib/store/todoStore";
    import tagStore from "./lib/store/tagStore";
    import MainContainer from "./lib/components/MainContainer.svelte";

    onMount(() => {
        todoStore.loadLocal()
        tagStore.loadLocal()
    })

</script>

<div class="flex w-full justify-center">
    <div class="w-[48rem]">
        <MainContainer />
    </div>
</div>

// packages/solid-project/src/App.tsx
import { onMount } from 'solid-js';
import './App.css';
import MainContainer from './components/MainContainer';
import todoStore from './stores/TodoStore';
import tagStore from './stores/TagStore';

function App() {
  const { loadLocal: loadLocalTodo } = todoStore;
  const { loadLocal: loadLocalTag } = tagStore;

  onMount(() => {
    loadLocalTodo();
    loadLocalTag();
  });

  return (
    <MainContainer />
  );
}

export default App;
