// packages/solid-project/src/components/styledComponents/NumericInput.tsx
import { ComponentProps } from "solid-js";

interface NumericInputProps {
  value: number;
  min: number;
  max: number
}

export default function NumericInput(props: ComponentProps<'input'> & NumericInputProps) {
    return (
        <input
            {...props}
            type="number"
            min={props.min}
            max={props.max}
            value={props.value}
        />
    )
}

// packages/vue-project/src/components/common/NumericInput.vue
<script setup lang="ts">
interface NumericInputProps {
  modelValue: number;
  min: number;
  max: number
}

const props = defineProps<NumericInputProps>();
defineEmits(['update:modelValue']);
</script>

<template>
  <input
    type="number"
    :min="props.min"
    :max="props.max"
    :value="props.modelValue"
    @change="$emit('update:modelValue', Number($event.target.value)) "
  >
</template>
