// packages/vue-project/src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import MainContainer from './components/Todo/MainContainer.vue';
import { todoStore, tagStore } from './utils/store';

onMounted(() => {
  todoStore.loadLocal();
  tagStore.loadLocal();
});

</script>

<template>
  <MainContainer class="wanted-sans" />
</template>

// packages/svelte-project/src/App.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import todoStore from "./lib/store/todoStore";
    import tagStore from "./lib/store/tagStore";
    import MainContainer from "./lib/components/MainContainer.svelte";

    onMount(() => {
        todoStore.loadLocal()
        tagStore.loadLocal()
    })

</script>

<div class="flex w-full justify-center">
    <div class="w-[48rem]">
        <MainContainer />
    </div>
</div>
