// packages/vue-project/src/components/Todo/MainContainer.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';
import { todoStore, tagStore } from '../../utils/store';

import SingleTodo from './SingeTodo.vue';
import TodoAddForm from './TodoAddForm.vue';
import TagAddForm from './TagAddForm.vue';

import VueIcon from '../Icons/VueIcon.vue';
import ViteIcon from '../Icons/ViteIcon.vue';
import StyledTitle from '../common/StyledTitle.vue';

onMounted(() => {
  todoStore.subscribe();
  tagStore.subscribe();
});
onUnmounted(() => {
  todoStore.unsubscribe();
  tagStore.unsubscribe();
});
</script>

<template>
  <div class="flex flex-col place-items-center space-y-12 wanted-sans">
    <div class="space-y-4 w-full">
      <StyledTitle>
        <div class="flex items-center justify-center">
          Vue
          <VueIcon class="w-16 h-16" />
          +
          Vite
          <ViteIcon class="w-16 h-16" />
        </div>
      </StyledTitle>
    </div>

    <div className="space-y-4 w-full">
      <StyledTitle>📝 할 일 추가하기</StyledTitle>
      <TodoAddForm />
    </div>
    <div className="space-y-4 w-full">
      <StyledTitle>#️⃣ 태그 추가하기</StyledTitle>
      <TagAddForm />
    </div>

    <div className="space-y-4 w-full">
      <StyledTitle>⛳ 할 일 목록</StyledTitle>
      <SingleTodo
        v-for="todo in todoStore.todos.value"
        :key="todo.title"
        :todo="todo"
      />
    </div>
  </div>
</template>

// packages/solid-project/src/components/MainContainer.tsx
import { Index, onMount } from 'solid-js';

import todoStore from '../stores/TodoStore';
import tagStore from '../stores/TagStore';

import SingleTodo from './SingleTodo';
import StyledTitle from './styledComponents/StyledTitle';
import TagAddForm from './TagAddForm';
import TodoAddForm from './TodoAddForm';
import ViteIcon from './Icons/ViteIcon';
import SolidIcon from './Icons/SolidIcon';

export default function MainContainer() {
  onMount(() => {
    todoStore.subscribe();
    tagStore.subscribe();
    return (() => {
      todoStore.unsubscribe();
      tagStore.unsubscribe();
    });
  });

  return (
    <div class="flex flex-col place-items-center space-y-12 wanted-sans">
      <div class="space-y-4 w-full">
        <StyledTitle>
          <div class="flex items-center justify-center">
            Solid
            <SolidIcon class="w-16 h-16" />
            +
            Vite
            <ViteIcon class="w-16 h-16" />
          </div>
        </StyledTitle>
      </div>

      <div class="space-y-4 w-full">
        <StyledTitle>📝 할 일 추가하기</StyledTitle>
        <TodoAddForm />
      </div>

      <div class="space-y-4 w-full">
        <StyledTitle>#️⃣ 태그 추가하기</StyledTitle>
        <TagAddForm />
      </div>

      <div class="space-y-4 w-full">
        <StyledTitle>⛳ 할 일 목록</StyledTitle>
        <Index each={todoStore.todos}>
          {(todo) => (
            <SingleTodo todo={todo()} />
          )}
        </Index>
      </div>

    </div>
  );
}
