// packages/svelte-project/src/lib/components/SingleTodo.svelte
<script lang="ts">
    export let todo: Todo
    import { Todo, dueDateFormatter, yyyymmdd } from "@todo-mono/shared";
    import todoStore from "../store/todoStore";
    import StyledButton from "./styledComponents/StyledButton.svelte";
    import RoundContainer from "./styledComponents/RoundContainer.svelte";

    let isCompletedOpen = false
    
    function handleComplete() {
      const memo = window.prompt('완료를 축하합니다. 메모를 남겨주세요.')
      todoStore.addCompleted(todo, memo || '완료')
    }
</script>

<div class="flex-col space-y-4 border-2 border-slate-800 p-4 rounded-lg">
    <div class="flex items-center space-x-2">
      <span>
        { dueDateFormatter(todo.dueDate)}
      </span>
    </div>

    <div class="flex items-center p-2 border-slate-800 border-2 rounded-lg justify-between">
      <span>
        { todo.title }
      </span>
      <StyledButton on:click={handleComplete}>
        완료처리
      </StyledButton>
    </div>

    <div class="flex space-x-1">
      <RoundContainer class="bg-amber-400">
        중요도:
        { todo.importance }
      </RoundContainer>
      <RoundContainer class="bg-orange-400">
        반복 주기:
        { todo.repeatInterval }
        일
      </RoundContainer>
      {#each todo.tags as tag}
          <RoundContainer style="background-color: {tag.color} ">
            { tag.name }
          </RoundContainer>
        {/each}
    </div>

    <StyledButton
      class="w-full"
      on:click={() => isCompletedOpen = !isCompletedOpen}
    >
      { isCompletedOpen ? '완료 내역 닫기' : '완료 내역 보기' }
    </StyledButton>

    {#if isCompletedOpen}
      <div
        class="flex flex-col bg-gray-200 rounded-lg"
      >
        {#each todo.completed as record}
            <span
              class="flex justify-between items-center p-2"
            >
              { record.memo }
              <RoundContainer class="bg-slate-400">
                { yyyymmdd(record.completed) }
              </RoundContainer>
            </span>
        {/each}
      </div>
    {/if}
  </div>

// packages/solid-project/src/components/SingleTodo.tsx
import { For, Show, createSignal } from 'solid-js';
import { dueDateFormatter, yyyymmdd } from '@todo-mono/shared';
import StyledButton from './styledComponents/StyledButton';
import RoundedContainer from './styledComponents/RoundedContainer';
import todoStore from '../stores/TodoStore';

export default function SingleTodo(props: { todo: DeserializedTodo }) {
  const { addComplete } = todoStore;
  const [isCompletedOpen, setIsCompletedOpen] = createSignal(false);
  const onComplete = (todo: DeserializedTodo) => {
    const memo = window.prompt('완료를 축하합니다. 메모를 남겨주세요')
    addComplete(todo, memo || ' ');
  };

  return (
    <div class="flex-col space-y-4 border-2 border-slate-800 p-4 rounded-lg">
      <div class="flex items-center space-x-2">
        <span>
          { dueDateFormatter(props.todo.dueDate) }
        </span>
      </div>

      <div class="flex items-center p-2 border-slate-800 border-2 rounded-lg justify-between">
        <span>
          { props.todo.title }
        </span>
        <StyledButton onClick={[onComplete, props.todo]}>
          완료처리
        </StyledButton>
      </div>

      <div class="flex space-x-1">
        <RoundedContainer class="bg-amber-400">
          중요도:
          { props.todo.importance }
        </RoundedContainer>
        <RoundedContainer class="bg-orange-400">
          반복 주기:
          { props.todo.repeatInterval }
          일
        </RoundedContainer>
        <For each={props.todo.tags}>
          {(tag) => (
            <RoundedContainer
              style={{ background: tag.color }}
            >
              { tag.name }
            </RoundedContainer>
          )}
        </For>
      </div>

      <StyledButton
        class="w-full"
        onClick={() => setIsCompletedOpen(!isCompletedOpen())}
      >
        { isCompletedOpen() ? '완료 내역 닫기' : '완료 내역 보기' }
      </StyledButton>

      <Show when={isCompletedOpen()}>
        <div
          class="flex flex-col bg-gray-200 rounded-lg"
        >
          <For each={props.todo.completed}>
            {(record) => (
              <span
                class="flex justify-between items-center p-2"
              >
                { record.memo }
                <RoundedContainer class="bg-slate-400">
                  { yyyymmdd(record.completed) }
                </RoundedContainer>
              </span>
            )}

          </For>
        </div>
      </Show>
    </div>
  );
}
