// packages/preact-project/src/lib/components/SingleTodo.tsx
import { type Dispatch } from 'preact/hooks';
import { useState } from 'preact/hooks';
import { Todo, dueDateFormatter, yyyymmdd } from '@todo-mono/shared';
import { TodoAction } from '../types/Hooks';

import RoundContainer from './styledComponents/RoundContainer';
import StyledButton from './styledComponents/StyledButton';

function SingleTodo(props: { todo: Todo, dispatch: Dispatch<TodoAction> }) {
  const [isCompletedOpen, setIsCompletedOpen] = useState(false);
  const { todo, dispatch } = props;

  const onComplete = () => {
    // eslint-disable-next-line no-alert
    const memo = window.prompt('완료를 축하합니다. 메모를 남겨주세요') || '완료';
    dispatch({ type: 'addCompleted', payload: { todo, memo } });
  };

  return (
    <div className="flex-col space-y-4 border-2 border-slate-800 p-4 rounded-lg">
      <div className="flex items-center space-x-2">
        <span>
          { dueDateFormatter(todo.dueDate) }
        </span>
      </div>

      <div className="flex items-center p-2 border-slate-800 border-2 rounded-lg justify-between">
        <span>
          { todo.title }
        </span>
        <StyledButton onClick={onComplete}>
          완료처리
        </StyledButton>
      </div>

      <div className="flex space-x-1">
        <RoundContainer className="bg-amber-400">
          중요도:
          {' '}
          { todo.importance }
        </RoundContainer>
        <RoundContainer className="bg-orange-400">
          반복 주기:
          {' '}
          { todo.repeatInterval }
          일
        </RoundContainer>
        {todo.tags.map((tag, idx) => (
          // DEBUG idx in key
          <RoundContainer key={`${tag.name} ${String(idx)}`} style={{ 'background': tag.color }}>
            { tag.name }
          </RoundContainer>
        ))}
      </div>

      <StyledButton
        className="w-full"
        onClick={() => setIsCompletedOpen(!isCompletedOpen)}
      >
        { isCompletedOpen ? '완료 내역 닫기' : '완료 내역 보기' }
      </StyledButton>

      {isCompletedOpen && (
        <div className="flex flex-col bg-gray-200 rounded-lg">
          {todo.completed.map((record, idx) => (
            <span key={`${record.memo} ${String(idx)}`} className="flex justify-between items-center p-2">
              { record.memo }
              <RoundContainer className="bg-slate-400">
                { yyyymmdd(record.completed) }
              </RoundContainer>
            </span>
          ))}
        </div>
      ) : (null)}
    </div>
  );
}

export default SingleTodo;

// packages/solid-project/src/components/SingleTodo.tsx
import { Index, Show, createSignal } from 'solid-js';
import { dueDateFormatter, yyyymmdd } from '@todo-mono/shared';
import { DeserializedTodo } from '../types/todoType';
import todoStore from '../stores/TodoStore';
import RoundedContainer from './styledComponents/RoundedContainer';
import StyledButton from './styledComponents/StyledButton';

export default function SingleTodo(props: { todo: DeserializedTodo }) {
  const { addComplete } = todoStore;
  const [isCompletedOpen, setIsCompletedOpen] = createSignal(false);
  const onComplete = (todo: DeserializedTodo) => {
    // eslint-disable-next-line no-alert
    const memo = window.prompt('완료를 축하합니다. 메모를 남겨주세요');
    addComplete(todo, memo || ' ');
  };

  return (
    <div class="flex-col space-y-4 border-2 border-slate-800 p-4 rounded-lg">
      <div class="flex items-center space-x-2">
        <span>
          { dueDateFormatter(props.todo.dueDate) }
        </span>
      </div>

      <div class="flex items-center p-2 border-slate-800 border-2 rounded-lg justify-between">
        <span>
          { props.todo.title }
        </span>
        <StyledButton onClick={[onComplete, props.todo]}>
          완료처리
        </StyledButton>
      </div>

      <div class="flex space-x-1">
        <RoundedContainer class="bg-amber-400">
          중요도:
          { props.todo.importance }
        </RoundedContainer>
        <RoundedContainer class="bg-orange-400">
          반복 주기:
          { props.todo.repeatInterval }
          일
        </RoundedContainer>
        <Index each={props.todo.tags}>
          {(tag) => (
            <RoundedContainer
              style={{ background: tag().color }}
            >
              { tag().name }
            </RoundedContainer>
          )}
        </Index>
      </div>

      <StyledButton
        class="w-full"
        onClick={() => setIsCompletedOpen(!isCompletedOpen())}
      >
        { isCompletedOpen() ? '완료 내역 닫기' : '완료 내역 보기' }
      </StyledButton>

      <Show when={isCompletedOpen()}>
        <div
          class="flex flex-col bg-gray-200 rounded-lg"
        >
          <Index each={props.todo.completed}>
            {(record) => (
              <span
                class="flex justify-between items-center p-2"
              >
                { record().memo }
                <RoundedContainer class="bg-slate-400">
                  { yyyymmdd(record().completed) }
                </RoundedContainer>
              </span>
            )}
          </Index>
        </div>
      </Show>
    </div>
  );
}
