// packages/svelte-project/src/App.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import todoStore from "./lib/store/todoStore";
    import tagStore from "./lib/store/tagStore";
    import MainContainer from "./lib/components/MainContainer.svelte";

    onMount(() => {
        todoStore.loadLocal()
        tagStore.loadLocal()
    })

</script>

<div class="flex w-full justify-center">
    <div class="w-[48rem]">
        <MainContainer />
    </div>
</div>

// packages/react-project/src/App.tsx
import { useEffect, useReducer } from 'react';
import { todoReducer } from './lib/reducers/todoReducer';
import MainContainer from './lib/components/MainContainer';
import { tagReducer } from './lib/reducers/tagReducer';

function App() {
  const [todoState, todoDispatch] = useReducer(todoReducer, []);
  const [tagState, tagDispatch] = useReducer(tagReducer, []);
  useEffect(() => {
    todoDispatch({ type: 'loadLocal' });
    tagDispatch({ type: 'loadLocal' });
  }, []);

  return (
    <div className="flex justify-center">
      <div className="w-[48rem]">
        <MainContainer
          tags={tagState}
          tagDispatch={tagDispatch}
          todos={todoState}
          todoDispatch={todoDispatch}
        />
      </div>
    </div>
  );
}

export default App;
